# [ zrfisaac ]

# [ about ]
# - author : Isaac Caires
# . - email : zrfisaac@gmail.com
# . - site : zrfisaac.github.io

# [ dockerfile ]
# : - image
FROM container-registry.oracle.com/database/express:21.3.0-xe

# : - about
LABEL description="A Oracle image"
LABEL license="GPL-3.0"
LABEL maintainer="zrfisaac@gmail.com"
LABEL url="https://github.com/zrfisaac/stuff.docker"
LABEL version="0.0.1"

# : - variable
ENV ORACLE_PWD=ABcd!@34

# : - run
CMD ["tail", "-f", "/dev/null"]
