# [ zrfisaac ]

# [ about ]
# - author : Isaac Caires
# . - email : zrfisaac@gmail.com
# . - site : zrfisaac.github.io

# [ dockerfile ]
# : - image
FROM ubuntu:latest

# : - about
LABEL description="A Ubuntu image"
LABEL license="GPL-3.0"
LABEL maintainer="zrfisaac@gmail.com"
LABEL url="https://github.com/zrfisaac/stuff.docker"
LABEL version="0.0.1"

# : - run
CMD ["tail", "-f", "/dev/null"]
